# Jekyll configuration

name: Bruna Junqueira Lopes
description: Things I did =]

# Url is currently only used only for the RSS feed in feed.xml
url: http://brunaafl.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: '/'

author: Bruna Junqueira Lopes
copyright: 2024

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github: brunaafl
  linkedin: brunajaflopes
  lastfm: Burnana

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: brunaafl
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
